#pragma once
// Generated by cpp_impl/play_book_pack.cpp (payload format 2). Do not edit; see documentation/play_book.md.
// No book: the text book is empty. pb_init decodes nothing and pb_lookup never finds a move, so the
// bot searches every move after its hard-coded center-center opener. Packing a non-empty text book
// (make play-book) brings a book back.

static constexpr int PLAY_BOOK_FORMAT = 2;
static constexpr int PLAY_BOOK_ENTRIES = 0;
static constexpr int PLAY_BOOK_BYTES = 0;
// pb_eval_fingerprint of the net the moves were ordered with; 0: no book, packed with no net.
static constexpr uint64_t PLAY_BOOK_EVAL_FINGERPRINT = 0ull;

static const char PLAY_BOOK_CJK[] = "";
