// Packs a text book (play_book_gen, or tools that write "S" lines) into
// play_book_data.hpp, payload format 2 (several moves per position; see
// play_book.hpp and play_book_text.hpp).
//
// Walks the book with the same PbWalker the CodinGame bot uses to decode it,
// so the stored order cannot drift from the runtime order, and codes each
// decision with the same adaptive binary models and the same NNUE evaluator
// (play_book.hpp), so the probabilities cannot drift either. The text book only
// lists our positions: an opponent reply is covered when it leads to one of
// them, and the book goes on after one of our moves when any reply is covered.
// A position listed on several "S" lines with its seq stores each listed move
// (at most PB_MAX_MOVES; the first is the primary) and the walk follows each
// of them; a line reaching it by another seq adds nothing (a warning when its
// move differs; play_book_text.hpp).
// Fails if a position lists more than PB_MAX_MOVES moves, if a line's move is
// illegal, if a line is past the 25-ply cap (a seq of more than 24 moves), if
// the walk reaches a position the text book lacks, or if any text-book entry
// is never reached (for example a line that does not start from
// center-center). The coding itself is in play_book_pack.hpp.
//
//   play_book_pack <book.txt> <out.hpp>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "global_board.hpp"
#include "crossfish_dev.hpp"
#include "play_book_text.hpp"
#define PLAY_BOOK_NO_DATA
#include "play_book.hpp"
#include "play_book_pack.hpp"  // the encoder, the walk hooks, the refusals and the walk

int main(int argc, char **argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: play_book_pack <book.txt> <out.hpp>\n");
        return 2;
    }
    Book book;
    if (!book.load(argv[1])) { std::fprintf(stderr, "cannot load %s\n", argv[1]); return 1; }
    // Illegal moves, the 25-ply cap, at most PB_MAX_MOVES distinct moves per position.
    int alt_total = 0;
    std::string refusal = pb_pack_refusal(book, alt_total);
    if (!refusal.empty()) {
        std::fprintf(stderr, "%sNot packed.\n", refusal.c_str());
        return 1;
    }
    if (book.transposed)  // format 1's merge: the first line of a position stands
        std::fprintf(stderr,
                     "warning: %d line(s) reach a listed position by another seq with another move; their "
                     "moves are ignored (only lines with the position's own seq add moves). The first: %s\n",
                     book.transposed, book.first_transposed.c_str());
    crossfish_nnue_load_once();

    PackHooks hooks{book};
    int entries = 0;
    std::string err;
    if (!pb_pack(hooks, alt_total, entries, err)) {
        std::fprintf(stderr, "%s\n", err.c_str());
        return 1;
    }
    std::vector<unsigned char> &bytes = hooks.enc.out;
    double info_bits = hooks.uniform_bits;
    std::string text = encode_u15(bytes);
    size_t chars = 0;
    for (unsigned char ch : text) chars += (ch & 0xC0) != 0x80 && ch != '\n';

    FILE *f = std::fopen(argv[2], "wb");
    if (!f) { std::fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
    std::fprintf(f,
        "#pragma once\n"
        "// Generated by cpp_impl/play_book_pack.cpp (payload format 2). Do not edit; see documentation/play_book.md.\n"
        "// %d of our positions (%d with 2 moves, %d with 3 moves) and %d opponent positions whose\n"
        "// replies it covers, after the first player's center-center.\n\n"
        "static constexpr int PLAY_BOOK_FORMAT = 2;\n"
        "static constexpr int PLAY_BOOK_ENTRIES = %d;\n"
        "static constexpr int PLAY_BOOK_BYTES = %zu;\n"
        "// pb_eval_fingerprint of the net the moves were ordered with; pb_init refuses the payload under another.\n"
        "static constexpr uint64_t PLAY_BOOK_EVAL_FINGERPRINT = %lluull;\n\n"
        "static const char PLAY_BOOK_CJK[] = R\"~(\n%s\n)~\";\n",
        entries, hooks.by_count[2], hooks.by_count[3], hooks.expanded + 1, entries, bytes.size(),
        (unsigned long long)pb_eval_fingerprint(hooks.eval), text.c_str());
    std::fclose(f);
    std::printf("packed %d positions (%d expanded opponent positions; %d with 2 moves, %d with 3 moves): %.0f bits "
                "as plain digits, coded to %zu bytes, %zu payload characters -> %s\n",
                entries, hooks.expanded + 1, hooks.by_count[2], hooks.by_count[3], info_bits, bytes.size(),
                chars, argv[2]);
    return 0;
}
