// Packs a full-coverage text book (from play_book_gen) into play_book_data.hpp.
//
// Walks the book with the same PbWalker the CodinGame bot uses to decode it,
// so the stored order cannot drift from the runtime order. Fails if the walk
// reaches a position the text book lacks, or if any text-book entry is never
// reached (e.g. the depths do not match the ones the book was generated with).
//
//   play_book_pack <book.txt> <out.hpp> <depth_first> <depth_second>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "global_board.hpp"
#include "play_book_text.hpp"
#define PLAY_BOOK_NO_DATA
#include "play_book.hpp"

// Same bit layout as tools/nnue_cjk14.py: 14-bit groups, MSB first, from U+4E00.
static std::string encode_cjk14(const std::vector<unsigned char> &data) {
    std::string out;
    uint32_t acc = 0;
    int bits = 0, column = 0;
    auto emit = [&](uint32_t v) {
        uint32_t code = 0x4E00 + v;
        out += (char)(0xE0 | (code >> 12));
        out += (char)(0x80 | ((code >> 6) & 63));
        out += (char)(0x80 | (code & 63));
        if (++column == 64) { out += '\n'; column = 0; }
    };
    for (unsigned char byte : data) {
        acc = (acc << 8) | byte;
        bits += 8;
        while (bits >= 14) {
            bits -= 14;
            emit((acc >> bits) & 0x3FFF);
        }
        acc &= (1u << bits) - 1;
    }
    if (bits) emit((acc << (14 - bits)) & 0x3FFF);
    if (column == 0 && !out.empty()) out.pop_back();
    return out;
}

int main(int argc, char **argv) {
    if (argc < 5) {
        std::fprintf(stderr, "usage: play_book_pack <book.txt> <out.hpp> <depth_first> <depth_second>\n");
        return 2;
    }
    Book book;
    if (!book.load(argv[1])) { std::fprintf(stderr, "cannot load %s\n", argv[1]); return 1; }
    int depth_first = std::atoi(argv[3]), depth_second = std::atoi(argv[4]);

    std::vector<std::pair<int, int>> digits;  // (index, radix)
    int missing = 0;
    auto choose = [&](GlobalBoard &b, Move *legal, int n) {
        Move m;
        int index = 0;
        if (book.lookup(b, m)) {
            for (int i = 0; i < n; i++)
                if (legal[i].mini_board == m.mini_board && legal[i].square == m.square) index = i;
        } else {
            missing++;
        }
        digits.push_back({index, n});
        return index;
    };
    PbWalker<GlobalBoard, Move, decltype(choose)> walker{choose};
    walker.run(depth_first, depth_second);
    if (missing || walker.entries != (int)book.entries.size()) {
        std::fprintf(stderr, "walk/book mismatch: walk visited %d positions, text book has %zu, %d missing\n",
                     walker.entries, book.entries.size(), missing);
        return 1;
    }

    // Mixed radix in 56-bit chunks, mirroring PbReader exactly.
    std::vector<uint64_t> chunks;
    uint64_t range = ~0ull, mult = 1;
    double info_bits = 0;
    for (auto &d : digits) {
        uint64_t radix = (uint64_t)d.second;
        if (range > (1ull << 56) / radix) { chunks.push_back(0); range = 1; mult = 1; }
        chunks.back() += (uint64_t)d.first * mult;
        mult *= radix;
        range *= radix;
        info_bits += std::log2((double)radix);
    }
    std::vector<unsigned char> bytes;
    for (uint64_t c : chunks)
        for (int i = 0; i < 7; i++) bytes.push_back((unsigned char)(c >> (8 * i)));
    std::string text = encode_cjk14(bytes);
    size_t chars = 0;
    for (unsigned char ch : text) chars += (ch & 0xC0) != 0x80 && ch != '\n';

    FILE *f = std::fopen(argv[2], "wb");
    if (!f) { std::fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
    std::fprintf(f,
        "#pragma once\n"
        "// Generated by cpp_impl/play_book_pack.cpp. Do not edit; see documentation/play_book.md.\n"
        "// %d positions: every opponent reply covered through our %d stored moves when\n"
        "// moving first (after center-center) and %d when moving second.\n\n"
        "static constexpr int PLAY_BOOK_DEPTH_FIRST = %d;\n"
        "static constexpr int PLAY_BOOK_DEPTH_SECOND = %d;\n"
        "static constexpr int PLAY_BOOK_ENTRIES = %d;\n"
        "static constexpr int PLAY_BOOK_BYTES = %zu;\n\n"
        "static const char PLAY_BOOK_CJK[] = R\"~(\n%s\n)~\";\n",
        walker.entries, depth_first, depth_second, depth_first, depth_second, walker.entries, bytes.size(),
        text.c_str());
    std::fclose(f);
    std::printf("packed %d positions: %.0f information bits, %zu bytes, %zu payload characters -> %s\n",
                walker.entries, info_bits, bytes.size(), chars, argv[2]);
    return 0;
}
